// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// WorkspacesColumns holds the columns for the "workspaces" table.
	WorkspacesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// WorkspacesTable holds the schema information for the "workspaces" table.
	WorkspacesTable = &schema.Table{
		Name:       "workspaces",
		Columns:    WorkspacesColumns,
		PrimaryKey: []*schema.Column{WorkspacesColumns[0]},
	}
	// WorkspaceUsersColumns holds the columns for the "workspace_users" table.
	WorkspaceUsersColumns = []*schema.Column{
		{Name: "workspace_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// WorkspaceUsersTable holds the schema information for the "workspace_users" table.
	WorkspaceUsersTable = &schema.Table{
		Name:       "workspace_users",
		Columns:    WorkspaceUsersColumns,
		PrimaryKey: []*schema.Column{WorkspaceUsersColumns[0], WorkspaceUsersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "workspace_users_workspace_id",
				Columns:    []*schema.Column{WorkspaceUsersColumns[0]},
				RefColumns: []*schema.Column{WorkspacesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "workspace_users_user_id",
				Columns:    []*schema.Column{WorkspaceUsersColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
		WorkspacesTable,
		WorkspaceUsersTable,
	}
)

func init() {
	WorkspaceUsersTable.ForeignKeys[0].RefTable = WorkspacesTable
	WorkspaceUsersTable.ForeignKeys[1].RefTable = UsersTable
}
