/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as Hello_worldRouteImport } from './../routes/hello_world'
import { Route as IndexRouteImport } from './../routes/index'

const Hello_worldRoute = Hello_worldRouteImport.update({
  id: '/hello_world',
  path: '/hello_world',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hello_world': typeof Hello_worldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hello_world': typeof Hello_worldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hello_world': typeof Hello_worldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hello_world'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hello_world'
  id: '__root__' | '/' | '/hello_world'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Hello_worldRoute: typeof Hello_worldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hello_world': {
      id: '/hello_world'
      path: '/hello_world'
      fullPath: '/hello_world'
      preLoaderRoute: typeof Hello_worldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Hello_worldRoute: Hello_worldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
